[package]
name = "counter"
version = "0.1.0"
edition = "2024"
description = """A word frequency counter CLI tool similar to python counted dicts"""

[dependencies]
anyhow = "1.0.103"
clap = { version = "4.6.1", features = ["derive"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

unwrap_used = "deny"
expect_used = "deny"
todo = "deny"
unimplemented = "deny"
panic = "deny"
panic_in_result_fn = "deny"
indexing_slicing = "deny"
as_conversions = "deny"
